# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39c03e9bd03f72af5c592a000e53ff7c623b7238a64606f11b074c6ea8e6daf14a610fefdb4b63c76a8f0ee4f4cec49f7529790ab1d957e8138fdaff0e5def5

test:
  secret_key_base: 859e6b16679467466863fda213742c6d0eb886ede43d098108ef275e3c4b1c4f0180ab8864e357decf5348d2a1b0bd76e6174928f38a757ce0cc4705f6336b83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
