def get_question_data
question_data = {
  "cli" => {:name=>"CLI",
:question_text=>"Why would a developer prefer the command line over a GUI?"},
# :question_text=>"Write a command to list only files beginning with your first name and label the parts of the command",
# :question_text=>"Where can we find help for shell commands?",
# :question_text=>"List 4 bash commands for managing folders and files",
# :question_text=>"Describe 2 unsafe commands",
# :question_text=>"What's the difference between absolute and relative paths?"},
  "git" => {:name=>"Git",
:question_text=>"What's the difference between 'git commit' and 'git push'?"},
# :question_text=>"Describe the difference between a fork and a branch.",
# :question_text=>"Whiteboard the command(s) to create a new branch and swtich to it",
# :question_text=>"How often should you commit?",
# :question_text=>"Explain what a branch is in git.",
# :question_text=>"If you meant to fork before you cloned, but instead cloned from the original repo you might have trouble pushing. How can you fix this?"},
  "misc" => {:name=>"Misc",
:question_text=>"Describe what the DOM is and its importance in the web technology stack"},
# :question_text=>"Why would we want to take an object-oriented approach to programming?",
# :question_text=>"Describe how we use prototypes to set up inheritance in JS",
# :question_text=>"Write a JavaScript Object literal with at least one property and one method (e.g. a person).",
# :question_text=>"List common steps to follow when solving a problem.",
# :question_text=>"'I'm the world's #0 programmer!' Explain the joke.",
# :question_text=>"Create a CSS selector that selects all <li> elements with a class of 'nav-link'.",
# :question_text=>"What's the difference between an index and a key?",
# :question_text=>"What's the difference between an implicit return and a side effect?",
# :question_text=>"Explain the difference between referencing and invoking a function.",
# :question_text=>"Explain the concept of events and event driven programming.",
# :question_text=>"Explain the concept of a 'callback' function.",
# :question_text=>"What is binding.pry and how do we use it?",
# :question_text=>"Give an example usage of the 'link_to' method in Rails.",
# :question_text=>"What does it mean to use nested resources and why would you implement them?",
# :question_text=>"What is the purpose of `params`? Also list three ways in which Rails puts data in it.",
# :question_text=>"Explain what active record validations are for, and give an example of one.",
# :question_text=>"Describe the MVC (or rMVC) paradigm as it relates to Rails.",
# :question_text=>"Explain what ERB is and why we use it.",
# :question_text=>"Explain how to represent one-to-many relationships in AR (including DB columns).",
# :question_text=>"Explain what an ORM is and why they are useful.",
# :question_text=>"Define routes using Rails",
# :question_text=>"What is the purpose of Rails's application.html.erb file?",
# :question_text=>"Write an html <script> tag that links to a js file in public/js/app.js",
# :question_text=>"List the 5 HTTP request methods. How do they relate to the 4 crud actions?",
# :question_text=>"Whiteboard a Rails form helper that creates or edits an instance of a Student model.",
# :question_text=>"What is the difference between 'relative' and 'absolute' positioning?",
# :question_text=>"Describe the difference between a fork and a branch.",
# :question_text=>"List two Ruby Enumerators and give their purpose.",
# :question_text=>"Identify the three places that CSS styles can go",
# :question_text=>"Define the purpose of the 'action' and 'method' attributes of a form.",
# :question_text=>"Assuming a ActiveRecord class, name three methods that are added by `has_many :comments`",
# :question_text=>"What is the difference between Active Record methods find, find_by and where? Provide an example of each.",
# :question_text=>"Distinguish between a route and a path",
# :question_text=>"Explain what Handlebars is and why we use it.",
# :question_text=>"Define routes with URL parameters and access those parameters",
# :question_text=>"Whiteboard an ERD for an app with `doctors`, `patients` and `appointments` as models with ActiveRecord relationships.",
# :question_text=>"What is the difference between Active Record methods find, find_by and where? Provide an example of each.",
# :question_text=>"What is `npm`?",
# :question_text=>"Write a get request using any path as you would in an express application.",
# :question_text=>"How does `module.exports` help us with separation of concerns?",
# :question_text=>"Explain the `req` and `res` variables in `app.get('/authors', function(req, res){...})`",
# :question_text=>"Write an AJAX call that retrieves all the Artists from a Rails Tunr API, formatted as JSON.",
# :question_text=>"Write a Rails controller action which supports html and json responses.",
# :question_text=>"What does the HTML5 history api allow us to do?",
# :question_text=>"What is one problem that Single Page Applications face that traditional web apps don't?",
# :question_text=>"What are constructor functions? How do we use them?",
# :question_text=>"What is a prototype? Why do we care about them?",
# :question_text=>"List 1 Mongoose method and its ActiveRecord counterpart.",
# :question_text=>"How do callbacks and asynchronicity factor into Mongoose?",
# :question_text=>"Where should you declare associations in a Mongoose app?",
# :question_text=>"There are 3 different ways to set up your database tables in a Mongoose app. What are 2?",
# :question_text=>"Write a root route that redirects to '/authors'.",
# :question_text=>"What is an API?",
# :question_text=>"Give an example of each JSON data structure.",
# :question_text=>"Create a media query that supports most mobile phones.",
# :question_text=>"How can box sizing affect the DOM Element?",
# :question_text=>"Using a 'for' loop, iterate over an array of numbers in JavaScript, printing each to the console.",
# :question_text=>"List at least 3 methods added to a class when it inherits from ActiveRecord::Base.",
# :question_text=>"What action do you expect this route to perform: `app.post('/authors', function() {...}`?",
# :question_text=>"Write the url to request all authors from a Rails app, formatted as JSON."},
  "angular" => {:name=>"Angular",
:question_text=>"Instantiate an Angular module on the whiteboard. What arguments does it receive?"},
# :question_text=>"What is an IIFE? Why do we use them in Angular?",
# :question_text=>"What is an Angular directive? Provide three examples of one.",
# :question_text=>"How do we indicate something is an Angular expression in an HTML file?",
# :question_text=>"Why do we use the term 'ViewModel' in Angular?",
# :question_text=>"What type of Angular component is `ngResource`? What does it do?",
# :question_text=>"What is an Angular 'state'? What information do we need to define one?",
# :question_text=>"Why are custom directives useful in Angular?"},
#   "tdd js" => {:name=>"TDD JS"},
  "single page apps" => {:name=>"Single Page Apps",
:question_text=>"What does the HTML5 history api allow us to do?"},
# :question_text=>"What is one problem that Single Page Applications face that traditional web apps don't?"},
  "express" => {:name=>"Express",
:question_text=>"What is `npm`?"},
# :question_text=>"Write a get request using any path as you would in an express application.",
# :question_text=>"How does `module.exports` help us with separation of concerns?",
# :question_text=>"What action do you expect this route to perform: `app.post('/authors', function() {...}`?",
# :question_text=>"Explain the `req` and `res` variables in `app.get('/authors', function(req, res){...})`",
# :question_text=>"Write a root route that redirects to '/authors'."},
  "sequelize" => {:name=>"Sequelize",
:question_text=>"List 1 Sequelize method and its ActiveRecord counterpart."},
# :question_text=>"How do callbacks and asynchronicity factor into Sequelize?",
# :question_text=>"Where should you declare associations in a Sequelize app? ( Hint: Before or after you require your models? )",
# :question_text=>"There are 3 different ways to set up your database tables in a Sequelize app. What are 2?"},
  "apis" => {:name=>"APIs",
:question_text=>"What is a API?"},
# :question_text=>"Give an example of each JSON data structure.",
# :question_text=>"Write the url to request all authors from a Rails app, formatted as JSON.",
# :question_text=>"Write a Rails controller which supports html and json responses."},
  "rwd" => {:name=>"RWD",
:question_text=>"Create a media query that supports most mobile phones."},
  "css2" => {:name=>"CSS2",
:question_text=>"What is the difference between 'relative' and 'absolute' positioning?"},
# :question_text=>"What is a reliable source for 3rd party fonts?",
# :question_text=>"Name 2 pseudo-classes that allow css to add content to a page.",
# :question_text=>"How can box sizing affect the DOM Element?"},
  "databases" => {:name=>"Databases",
:question_text=>"What components are displayed on an ERD?"},
# :question_text=>"Draw an ERD for a Doctors, Patients, and Appointments.",
# :question_text=>"List common steps to follow when solving a problem.",
# :question_text=>"Draw an ERD for a Members, Magazines, and Subscriptions.",
# :question_text=>"Write the SQL statement to update the first_name of the 'author' whose ID is 12.",
# :question_text=>"Write the SQL statement to list the last names of everyone in the 'students' table."},
  "javascript" => {:name=>"Javascript",
:question_text=>"Describe the difference between what is truthy/falsey in Ruby vs JavaScript?"},
# :question_text=>"Using a 'for' loop, iterate over an array of numbers in JavaScript, printing each to the console.",
# :question_text=>"Explain the concept of a 'callback' function.",
# :question_text=>"Write a JavaScript Object literal with at least one property and one method (e.g. a person).",
# :question_text=>"Describe the difference between variables created with and without `var`.",
# :question_text=>"Define what a function is in Javascript and how it compares to a Ruby method.",
# :question_text=>"Differentiate between function declarations and expressions.",
# :question_text=>"Explain the concept of events and event driven programming.",
# :question_text=>"Explain the difference between synchronous and asynchronous execution.",
# :question_text=>"Explain the difference between referencing and invoking a function.",
# :question_text=>"What are Javascript's 5 primitive data types?",
# :question_text=>"What are the two types of collections in Javascript, and what are the differences between them?",
# :question_text=>"What's the difference between true / false and truthy / falsy?",
# :question_text=>"Use the whiteboard to create a Javascript function that has two arguments.",
# :question_text=>"What is pseudocode?",
# :question_text=>"What's the difference between an implicit return and a side effect?",
# :question_text=>"What is a loop? Give an example.",
# :question_text=>"'I'm the world's #0 programmer!' Explain the joke.",
# :question_text=>"What's the difference between an index and a key?",
# :question_text=>"Use Vanilla JS and jQuery to change a webpage's body background color to 'lemonchiffon'",
# :question_text=>"Define a function that takes a function as an argument and invokes the argument when the function is called."},
  "oojs" => {:name=>"OOJS",
:question_text=>"Write a JavaScript constructor function with at least one property and one method (e.g. a person). Create an instance."},
# :question_text=>"What are constructor functions? How do we use them?",
# :question_text=>"What is a prototype? Why do we care about them?",
# :question_text=>"Describe how we use prototypes to set up inheritance in JS",
# :question_text=>"What are constructor functions and the new keyword? How are they related?"},
  "ruby mvc" => {:name=>"Ruby MVC",
:question_text=>"Write a Ruby class with an initialize method."},
# :question_text=>"Explain what ERB is and why we use it.",
# :question_text=>"What is the purpose of `params`? Also list three ways in which Rails puts data in it.",
# :question_text=>"Explain how to represent one-to-many relationships in AR (including DB columns).",
# :question_text=>"Explain what active record validations are for, and give an example of one.",
# :question_text=>"Explain what an ORM is and why they are useful.",
# :question_text=>"Describe the MVC (or rMVC) paradigm as it relates to Rails.",
# :question_text=>"Give an example usage of the 'link_to' method in Rails.",
# :question_text=>"Describe what Rails is and what it is used for",
# :question_text=>"Distinguish between a route and a path",
# :question_text=>"Define routes using Rails",
# :question_text=>"What is the purpose of Rails' application.html.erb file?",
# :question_text=>"Write an html <script> tag that links to a js file in public/js/app.js",
# :question_text=>"List at least 3 methods added to a class when it inherits from ActiveRecord::Base.",
# :question_text=>"Define routes with URL parameters and access those parameters"},
  "ruby basics" => {:name=>"Ruby Basics",
:question_text=>"What are Ruby's 5 main data types?"},
# :question_text=>"What are the two types of collections in Ruby, and what are the differences between them?",
# :question_text=>"Describe the homework submission process for WDI.",
# :question_text=>"What is binding.pry and how do we use it?",
# :question_text=>"What's the difference between a symbol and a string?",
# :question_text=>"What's an enumerator?",
# :question_text=>"What's the difference between true / false and truthy / falsy?",
# :question_text=>"Use the whiteboard to create a Ruby method that has two arguments.",
# :question_text=>"What's the difference between explicit and implicit return?",
# :question_text=>"What is variable scope?",
# :question_text=>"How would you add a key / value pair to an existing hash?",
# :question_text=>"What is pseudocode?",
# :question_text=>"What's the difference between an implicit return and a side effect?",
# :question_text=>"What is a loop? Give an example.",
# :question_text=>"What's the difference between a loop and an enumerator?",
# :question_text=>"What's the difference between a range and an array?",
# :question_text=>"What's the difference between a variable and a method?",
# :question_text=>"What's the difference between 'break' and 'return'?",
# :question_text=>"Write a 'puts' statement on the board, and describe its input, output, and side effects.",
# :question_text=>"'I'm the world's #0 programmer!' Explain the joke.",
# :question_text=>"What's the difference between an index and a key?",
# :question_text=>"List two Ruby Enumerators and give their purpose.",
# :question_text=>"Describe the difference between what is truthy/falsey in Ruby vs JavaScript?",
# :question_text=>"How many objects can a method return? Which methods don't return anything?"},
  "activeRecord" => {:name=>"ActiveRecord",
:question_text=>"List at least 3 methods added to a class when it inherits from ActiveRecord::Base."},
# :question_text=>"Explain what an ORM is and why they are useful."},
  "html and css" => {:name=>"HTML and CSS",
:question_text=>"Explain what HTML is and what problem it solves"},
# :question_text=>"Explain the different roles of HTML, CSS & JavaScript in the web technology stack",
# :question_text=>"Describe what the DOM is and its importance in the web technology stack",
# :question_text=>"Explain the purpose of HTML attributes",
# :question_text=>"Describe the differences between the <head> and <body> tags",
# :question_text=>"Describe how content other than HTML documents are organized and accessed on the web",
# :question_text=>"Create HTML elements using tags and attributes",
# :question_text=>"Create a well formed HTML document that nests elements within each other",
# :question_text=>"Include images on a webpage",
# :question_text=>"Link from one webpage to another",
# :question_text=>"Define what CSS is and explain its role in separation of concerns",
# :question_text=>"Identify the three places that CSS styles can go",
# :question_text=>"Explain what selectors are, and how they target HTML elements",
# :question_text=>"Explain the major parts of the box model",
# :question_text=>"Explain the difference between inline and block elements",
# :question_text=>"Create an external stylesheet, and link it into an HTML document",
# :question_text=>"Explain what selector specificity is, and how it is calculated",
# :question_text=>"Explain the use of multiple fonts using font-family",
# :question_text=>"Explain the difference between padding and margin",
# :question_text=>"What's the difference between 'relative' and 'absolute' positioning?",
# :question_text=>"Explain the purpose of HTML attributes.",
# :question_text=>"Create a media query that supports most mobile phones.",
# :question_text=>"How can box sizing affect a DOM Element?"},
  "http" => {:name=>"HTTP",
:question_text=>"Define the purpose of the 'action' and 'method' attributes of a form."}

}

return question_data
end
